repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # keep version here in sync with CI/CD and other modal repos
    rev: "v0.4.1"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
