repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # keep version here in sync with CI/CD
    rev: "v0.3.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
