[tool.pytest.ini_options]
filterwarnings = [
    "error::DeprecationWarning",
    "error::modal.exception.DeprecationError",
    "ignore::DeprecationWarning:pytest.*:",
]
pythonpath = [
    "06_gpu_and_ml/text-to-pokemon",
]

[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
no_strict_optional = true

# https://github.com/python/mypy/issues/10632
[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true
