name: setup-cached-python

description: Set up a shared Python environment with cached dependencies.

inputs:
  version:
    description: Which Python version to install
    required: false
    default: "3.11"
  dependencies:
    description: Whether to skip installing cached dependencies.
    required: false
    default: "no-skip"

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}

    - name: Install base packages
      shell: bash
      run: |
        pip install uv
        uv pip install --system pip setuptools wheel

    - name: Install Python packages
      if: ${{ inputs.dependencies != 'skip' }}
      shell: bash
      run: uv pip install --system -r internal/requirements.txt
