sample_proj:
  target: sqlite
  outputs:
    sqlite:
      type: sqlite
      threads: 1
      schema: "main"
      database: "database" # required but has no meaning for sqlite
      schemas_and_paths:
        main: "/db/main.db"
        jaffle_shop: "/raw/warehouse.db"
      schema_directory: "/db"
#    To use some real database/datawarehouse w/ credentials from Modal secrets,
#    you can use env_var references and attach a corresponding secret to your Modal
#    image/function:
#    pg:
#      type: postgres
#      host: "{{ env_var('PGHOST') }}"
#      port: 5432
#      schema: public
#      dbname: "{{ env_var('PGDATABASE') }}"
#      user: "{{ env_var('PGUSER') }}"
#      password: "{{ env_var('PGPASSWORD') }}"
