version: 1
default_environment: local
project_id: 3b1408e8-f8ba-4387-8167-95d8619585ac
environments:
  - name: local
    env:
      SQLITE_WAREHOUSE: warehouse
  - name: modal
plugins:
  extractors:
    - name: tap-csv
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
      config:
        files:
          - entity: customer
            path: downloads/jaffle_shop_customers.csv
            keys:
              - ID
              - FIRST_NAME
              - LAST_NAME
          - entity: orders
            path: downloads/jaffle_shop_orders.csv
            keys:
              - ID
              - USER_ID
              - ORDER_DATE
              - STATUS
  loaders:
    - name: target-sqlite
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/target-sqlite.git
      config:
        database: ${SQLITE_WAREHOUSE}
        batch_size: 50
  utilities:
    - name: download_sample_data
      namespace: utils
      pip_url: -e ${MELTANO_PROJECT_ROOT}/utils/
      executable: download_sample_data
