name: Build Docs
on:
  push:
    branches:
      - main
      - build-docs
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build the docs
    runs-on: ubuntu-20.04
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_MODAL_LABS_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: modal-egs

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install base packages
        shell: bash
        run: |
          pip install uv
          uv pip install --system setuptools wheel

      - name: Checkout modal repo
        uses: actions/checkout@v3
        with:
          repository: modal-labs/modal
          token: ${{ secrets.GH_PAT }}
          path: internal/modal
          fetch-depth: 1

      - name: Move modal repo and symlink
        run: |
          mv internal/modal ../modal
          ln -s ../modal/examples ./

      - name: Install modal development packages
        run: |
          uv pip install --system -r ../modal/requirements.dev.txt

      - name: Checkout client repo
        uses: actions/checkout@v3
        with:
          repository: modal-labs/modal-client
          token: ${{ secrets.GH_PAT }}
          path: internal/client
          fetch-depth: 1

      - name: Install client repo from superdirectory
        run: |
          mv internal/client ../client
          uv pip install --system -e ../client

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci --include=dev
        working-directory: ../modal/frontend

      - name: Compile protos
        run: |
          cd ../client && inv protoc type-stubs
          cd ../modal && inv protoc

      - name: Build the docs
        working-directory: ../modal
        run: |
          inv frontend-preview
