name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy example apps
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cached-python

      - name: Install Modal client package
        run: pip install modal-client

      - name: Modal token set
        run: |
          modal token set --token-id ${{ secrets.MODAL_MODAL_LABS_TOKEN_ID }} --token-secret ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}

      - name: Run deployment script
        run: |
          python3 example_deploy.py --no-dry-run