name: Check
on: push

jobs:
  black:
    name: Black
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install black
        run: pip install black

      - name: Black
        run: black --check .

  flake8:
    name: Flake8
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install flake8
        run: pip install flake8

      - name: Check flake8
        run: flake8 .

  isort:
    name: Isort
    runs-on: ubuntu-20.04

    steps:
      - name: Install isort
        run: pip install isort

      - name: Check isort
        run: isort . -c -v --profile black

  pytest:
    name: Pytest
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dev dependencies
        run: pip install pytest jupytext

      - name: Install the Modal client
        run: pip install modal-client

      - name: Run
        run: pytest -v .
