name: Check
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # keep version here in sync with .pre-commit-config.yaml and other modal repos
      - run: pip install ruff==0.2.1

      - run: ruff check

      - run: ruff format --check

  nbconvert:
    name: NbConvert
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install NbConvert
        run: pip install jupyter nbconvert

      - name: Check notebooks are cleaned
        run: |
          jupyter nbconvert --clear-output --inplace 11_notebooks/*.ipynb
          git diff --quiet && git diff --cached --quiet || exit 1

  pytest:
    name: Pytest
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        run: pip install pytest jupytext pydantic~=1.10

      - name: Install the Modal client
        run: pip install modal-client

      - name: Run
        run: pytest -v .
