name: Run examples
# TODO: work on naming

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:

# Cancel previous runs of the same PR but do not cancel previous runs on main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TERM: linux
  TERMINFO: /etc/terminfo
  MODAL_TOKEN_ID: ${{ secrets.MODAL_MODAL_LABS_TOKEN_ID }}
  MODAL_TOKEN_SECRET: ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}
  MODAL_ENVIRONMENT: main

jobs:
  # This job executes any examples that have changed
  run-changed:
    name: Run any changed examples
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the examples repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-cached-python

      # TODO: PASSING SECRET CURRENTLY NOT WORKING!
      - name: Run each changed example
        id: get-changed-files
        shell: bash
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' | grep -vE '^(misc|internal)/' || true)
          if [ -z "$files" ]; then
            echo "No changes found to any .py files in examples"
            exit 0
          fi
          while IFS= read -r file; do
            stem=$(basename "$file" .py)
            echo $stem
            python3 -m internal.run_example $stem
          done <<< "$files"
          wait
          # parallel version is treating failure as success
