name: Typecheck
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  mypy:
    name: MyPy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-cached-python

      - name: Run
        run: python3 internal/typecheck.py
